config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <%= link_to "Cancel", flats_path, class: "btn btn-danger" %>
<% end %>

app/views/flats/edit.html.erb
<div class="row justify-content-center">
  <div class="form col-6 mt-3 py-3">
    <h1>Edit Flat</h1>
    <%= render "form", flat: @flat %>
  </div>
</div>

app/views/flats/index.html.erb
<h1>All our Flats (<%= @flats.length %>)</h1>

<div class="row">
  <% @flats.each do |flat| %>
    <div class="col-4">
      <div class="card-index mb-3">
        <div class="card-header">
          <h5><%= flat.name %></h5>
          <p><%= flat.address %></p>
          <div class="d-flex">
            <div class="pr-1"><i class="fa-solid fa-user-group"></i>  <%= flat.number_of_guests %></div>
            <div class="px-2"><i class="fa-solid fa-euro-sign"></i>  <%= flat.price_per_night %></div>
          </div>
        </div>
        <div class="card-body d-flex justify-content-between">
          <%= link_to "More info", flat_path(flat) %>
          <div>
            <%= link_to '<i class="fa-solid fa-pen"></i>'.html_safe, edit_flat_path(flat)%>
            <%= link_to '<i class="fa-regular fa-trash-can"></i>'.html_safe, flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="row justify-content-center">
  <div class="form col-6 mt-3 py-3">
    <h1>Add a new Flat</h1>
    <%= render "form", flat: @flat %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="row">
  <div class="col-8">
    <div class="card my-3">
      <div class="card-header">
        <h1><%= @flat.name %></h1>
        <h5><%= @flat.address %></h5>
      </div>
    </div>

    <div class="card my-3">
      <div class="card-header">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>

    <div class="card my-3">
      <div class="card-header">
        <h3>Details</h3>
        <div class="d-flex">
          <div class="pr-1"><i class="fa-solid fa-user-group"></i>  <%= @flat.number_of_guests %></div>
          <div class="px-2"><i class="fa-solid fa-euro-sign"></i>  <%= @flat.price_per_night %></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-4">
    <div class="card my-3">
      <div class="card-header">
      <h5>Book this place!</h5>

      <div class="input-group mb-3">
        <span class="input-group-text" id="inputGroup-sizing-default">From: </span>
        <input placeholder="12/10/2017"type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text" id="inputGroup-sizing-default">To: </span>
        <input placeholder="18/10/2017"type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
      </div>

      <%= link_to "Book", "", class:"btn btn-success", id:"btn-book" %>
      </div>
    </div>

    <div class="card my-3">
      <div class="card-header d-flex justify-content-between">
        <div>Share</div>
        <div>
          <i class="fa-brands fa-square-facebook"></i>
          <i class="fa-brands fa-square-instagram"></i>          <i class="fa-brands fa-square-pinterest"></i>
          <i class="fa-solid fa-square-envelope"></i>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/flats">Simple Airbnb</a>
        <a href="/flats/new" class="btn btn-outline-primary">Add Flat</a>
      </div>
    </nav>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>